# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YerTostik' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YerTostik
  pod 'Reusable'
  pod 'Sugar'
  pod 'EasyPeasy'
  pod 'FolioReaderKit'
  pod 'Firebase/Core'

  target 'YerTostikTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YerTostikUITests' do
    inherit! :search_paths
    # Pods for testing
  end

endπ
